# Generated by Django 6.1.2 on 2026-10-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Uploaded profile picture', null=True, upload_to='avatars/'),
        ),
    ]
