# Generated by Django 6.1.2 on 2026-10-08 09:30

import certificates.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=certificates.models.generate_cert_number, max_length=50, unique=True)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(default='100% Course Mastery', max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
